server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://replica1:8002/eureka/
